### PR TITLE
Completed Group Capstone Activities

### PR DESCRIPTION
**Pull request by mrsamsharma**
- Followed every card and it's description to create this capstone project
- @alphayowakarindi was Student B and @mrsamsharma was Student A
- We used TV shows [API](https://api.tvmaze.com/shows/) to get 240 shows
- The data we used from the API is Title of the show, Image, Description.
- After then we used involvement API which records the likes and comments user wants to make
- Those likes and comments are then Posted to the API
- After that they are retrieved from the same API to display the result on the respective section
- The Design is pretty simple but I like to call this Website 'TV FLIX'
- [Link to the presentation video](https://drive.google.com/file/d/1_e5uBI6biwFd0IPSj4OO-cdlH74WdKYW/view?usp=sharing)

### CODE REVIEW

**Review by Nemwel-Boniface — CHANGES_REQUESTED** [review]
## Hello @mrsamsharma and @alphayowakarindi           :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have both done an amazing job with your capstone project:clap: I really commend you both for the efforts  you both made to make this project possible :partying_face: 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly make your pull request description more descriptive
- [ ] I have rechecked and I have realized that you did not make the presentation video. Kindly include it in your next review as it is a [project requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md) to do so.

image


_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁 
# Hello Team! 😃 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] As requested by the previous Code Reviewer, Please record a video in which you guys are presenting your project showing different features of the project, and don't forget to mention your favorite piece of code 😃 We'd love to see it.
You can record a video on Loom or any other tool that you like. Best of Luck! :D

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alphayowakarindi** [comment]
@zainsadaqat Hi, the video was already there at the time of your review. Kindly, check the last line in the pull request description.

**Comment by zainsadaqat** [comment]
Hey @alphayowakarindi,

Please update your README file and add the presentation video link there so that other visitors could watch this as well. 👍🏻

**Comment by alphayowakarindi** [comment]
@zainsadaqat It's done, thank you.

**Review by zainsadaqat — APPROVED** [review]
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey Team! 😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
